services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\OverseasBundle\:
        resource: '../../../src/{Client, Service}'

    Answear\OverseasBundle\ConfigProvider: ~

