services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\OverseasBundle\:
        resource: '../../../src/{Client,Service,Serializer}'

    Answear\OverseasBundle\ConfigProvider: ~

    Answear\OverseasBundle\Logger\OverseasLogger:
        shared: false

